### ISSUE TITLE
Blog post link item shows 'Link copied!' on hover (before click)

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#113]
**Short description**: When hovering the link item (under Share), the purple text bubble 'Link copied!' is shown (even before clicking the icon - and thus without the link actually being copied).

**URL**: e.g. https://antennapod.org/blog/2020/12/new-website

**More info**: Issue probably is somewhere here: https://github.com/AntennaPod/antennapod.github.io/blob/master/_includes/share.html

**Comment by shuuji3** [comment]
Hi, it seems that this issue has been fixed by #233. I can see that the current page has no problem like this.🙂
