### ISSUE TITLE
Update setup-ruby action

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#116]
**Short description**: The action that builds the website has a job using an action that is no longer maintained.

**URL**: n/a

**More info**: 
> Run actions/setup-ruby@v1
> ------------------------
> NOTE: This action is deprecated and is no longer maintained.
> Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.

**Comment by Rotzbua** [comment]
@keunes fixed by #206
