### ISSUE TITLE
Add spanish from delthia/antennapod.github.io

### ISSUE THREAD

**Issue by delthia** [AntennaPod/antennapod.github.io#148]
Hello,
This is my first time trying to contribute to a project like this, so I didn't know how to do, but I have already translated the site into spanish and tested that it works with jekyll on my own computer. 
**Short description**: 
I would like for my spanish translation of the site and documentation to be added to the production site.

**Location**: 
It should be added as a new language.

**Why have this**: 
I think that the more languages that the documentation is in, the better for the community and adoption of the app.

**More info**: 

I have already translated it in a fork in https://github.com/delthia/antennapod.github.io.

I would like for the maintainers to tell me how to proceed, as I have never made a pull request.

Thanks, Iago

**Comment by keunes** [comment]
Hi @delthia!

Thanks for your interest in contributing translations. If you translated also the documentation section, you might have seen the texts on this page: https://antennapod.org/contribute/translate

There we explain the process. As written, we use Weblate for our translations, and the process is 95% automated. We therefore can't really accept a PR to bring translations to production, unfortunately. If you are interested in adding the translations on Weblate, please let me know!

**Comment by delthia** [comment]
Hello
Sorry if I misunderstood. I answered the notification email but I don't know if you were able to see it, so I will paste my reply here:
_Yes, it wouldn't be a problem for me to add the translations via weblate.
I have translated all the localised parts of the site, including the documentation and the contribute page.

Please tell me whenever the Spanish translation is opened in weblate, so I can add my translations._

I have since requested for the spanish language to be opened on the weblated project so I can add the translated texts.

Thanks, and sorry for any inconvenience I may cause

**Comment by keunes** [comment]
Hi
It seems the reply you sent to the notification email didn't reach the issue, but I did see the request on Weblate. I'm sorry I didn't get back to it earlier - I was away from my computer a few days. I've just activated it and it's available here:
https://hosted.weblate.org/languages/es/antennapod/

Thanks again! Let us know (ideally on the forum) if you have any questions or comments.

**Comment by delthia** [comment]
Hi,
I will add the translations later today

Ok, so I will take a look to the forum if I need something else.

Thanks

**Comment by delthia** [comment]
Hi!
Yes, it wouldn't be a problem for me to add the translations via weblate.
I have translated all the localised parts of the site, including the
documentation and the contribute page.

Please tell me whenever the Spanish translation is opened in weblate, so I
can add my translations.

Thanks
