### ISSUE TITLE
Documentation search doesn't return localised results, switches user language

### ISSUE THREAD

**Issue by loucasal** [AntennaPod/antennapod.github.io#159]
**Short description**: 
When using the search box on the documentation page, items are always displayed in EN despite having been translated (I understand they are part of the 'short strings' component).
Also, clicking on them switches the user language to EN. I would expect this second problem to become irrelevant once the first one is addressed.

**URL**: 
Both [live](https://antennapod.org/nl/documentation) and [test](https://deploy-preview-157--antennapod-test.netlify.app/it/documentation) environments are affected.

**Comment by keunes** [comment]
Hi @loucasal, I found a fix. It seems to work - you can test it here: https://deploy-preview-167--antennapod-test.netlify.app/

**Comment by loucasal** [comment]
Works for me, however I could only test it successfully with French and Dutch - for some reason, no results are displayed when using Italian.

**Comment by keunes** [comment]
Hmm, thanks. Will have a look.

**Comment by keunes** [comment]
Thanks again @loucasal. That should be fixed now :)

**Comment by loucasal** [comment]
I'm afraid we made a step backwards - all languages now display {title} where the strings should appear.

**Comment by keunes** [comment]
Oh my, sorry about that. I corrected it, then though I found a cleaner/more efficient solution, but didn't test that. Now it's really fixed. Should be on the live website soon. Thanks again!
