### ISSUE TITLE
User survey doesn't ask questions about non-standard podcast uses

### ISSUE THREAD

**Issue by jfinkhaeuser** [AntennaPod/antennapod.github.io#178]
**Short description**: 
To me, podcasts are lost information. I understand and accept that to many people they are enjoyable and in some cases the only means by which they are able to absorb information. I do not wish to give the impression that podcasts are a bad medium.

However, audio is very hard to search. It's very hard to skim through. It's not *my* medium.

As a consequence, I would love to see transcripts of every podcast. Most of my podcast consumption is reading of transcripts.

I understand as well that this requires extra work by the creators. I am not demanding that this happens.

However, in the context of this user survey, I would like to point out just how much transcripts are "make or break" for me (and I know I'm not the only person). Therefore, if you want to understand about how to add value to podcast/platforms, make the transcripts first class citizens.

Thank you!

**URL**: 
https://survey.antennapod.org/index.php/657295

**More info**: 
Relates to #177

**Comment by keunes** [comment]
Hi @jfinkhaeuser

The form is actually totally unrelated to transcripts. It is a way for us to find people who want to be interviewed about automation processes (automatic download/deletion). If you're interested in transcripts, please feel free to give a thumbs-up, follow and present your use-case here:
https://github.com/AntennaPod/AntennaPod/issues/4935

Best regards
