### ISSUE TITLE
Redirect information for podcasters

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#179]
**Short description**: Move the information for podcasters on redirects from GH wiki to our website

**Location**: documentation > for podcasters > take your subscribers to a new hosting provider

**Why have this**: easier to find, better to link on social media

**More info**: Text is here: https://github.com/AntennaPod/AntennaPod/wiki/Updated-feed-URLs-%28301-or-308-redirects%29

**Comment by loucasal** [comment]
This was completed in #338, so the ticket can be closed.
