### ISSUE TITLE
Improve documentation on Synchronisation

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#183]
**Short description**: Describe that synchronisation must happen via a central point, a server. That these servers can be offered by big parties shared by many users (risk: slow if not funded). Or that you can self-host a server (downside: more effort). Describe that 'address of webserver' is the URL of the server on which you have an account.

**Location**: https://antennapod.org/documentation/general/synchronization

**Why have this**: 
> Works well enough, but synchronizing between devices with gpodder is completely broken, and documentation is non-existent. When I try to set it up, it gives me a blank text box and wants me to enter "Host name". What does that even mean?? No documentation.

https://play.google.com/apps/publish?account=8008695526664634386#ReviewDetailsPlace:p=de.danoeh.antennapod&reviewid=3a5cfe15-4392-406f-b882-6fef6e040bd8

**More info**:

**Comment by Aliervo** [comment]
Love AntennaPod and would love to help out.  Mind if I take a pass at this?

**Comment by keunes** [comment]
Hi @Aliervo,

That's nice, thanks! Feel free to do a PR or propose a text here as a comment.

**Comment by loucasal** [comment]
This was completed in #191, so the ticket can be closed.
