### ISSUE TITLE
Add 'AntennaPod on the Linux desktop, iOS and Windows' page

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#210]
**Short description**: Add a page titled 'AntennaPod on the Linux desktop, iOS and Windows'. This page can contain a message 'AP is and will (for the foreseeing future) focus on Android' as well as our suggestions for great open source podcast apps/applications.
* Linux: https://vocalproject.net/, https://apps.kde.org/kasts/
* Windows: ??
* iOS: ??

**Location**: https://antennapod.org/documentation/general

**Why have this**: Quite a few people ask on Mastodon about linux desktop apps and "antennapod ios" (4th - 976 impressions through this search term the past 12 months) & "antennapod windows" (8th - 518) are relatively popular search terms to get to our website.

**More info**:

**Comment by ByteHamster** [comment]
Nice idea!

Kasts also runs on Windows (not officially, but there is a download link on the official page)
