### ISSUE TITLE
forum signup activation email broken

### ISSUE THREAD

**Issue by caoilte** [AntennaPod/antennapod.github.io#262]
### Checklist

- [X] I have used the search function for [open](https://github.com/AntennaPod/AntennaPod/issues) **and** [closed](https://github.com/AntennaPod/AntennaPod/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

x

### Where did you get the app from

Google Play

### Android version

x

### Expected behaviour

not this.

![image](https://github.com/AntennaPod/AntennaPod/assets/1500358/f601abab-4536-46ee-b651-d5f490c5d0d7)

### Current behaviour

oops. put screenshot in expected behaviour.

is not currently sending signup activation email. hasn't been for a while.

**Comment by ByteHamster** [comment]
Looks like this affected only gmail addresses. Apparently Google changed something in their anti-spam rules. Should be fixed now.

**Comment by caoilte** [comment]
lucky guess. can confirm that fixed it and have now been able to sign up.
