### ISSUE TITLE
Documentation says that Kasts does not support Windows

### ISSUE THREAD

**Issue by ByteHamster** [AntennaPod/antennapod.github.io#319]
**Short description**: 

The documentation says that Kasts does not support Windows. But it does.

**URL**: 

https://antennapod.org/documentation/general/other-platforms

**More info**:

**Comment by keunes** [comment]
How so actually, @ByteHamster? I only see 'Install on Linux' and 'Download on Flathub' (which is linux-only). Also the code readme doesn't mention windows.

**Comment by ByteHamster** [comment]
Hmm, I could swear there was a (quite hidden) button to download on Windows but now it seems it is no longer available. Then there is no point in keeping this issue open.
