### ISSUE TITLE
The Documentation does not address recovery from data loss

### ISSUE THREAD

**Issue by Ian2020** [AntennaPod/antennapod.github.io#33]
In reference to [my comment](https://github.com/AntennaPod/AntennaPod/issues/2463#issuecomment-655377377) on AntennaPod issue [2463](https://github.com/AntennaPod/AntennaPod/issues/2463)

>Could the FAQ not address this situation directly as it's potentially catastrophic?

I found myself victim of this bug and was unsure how to proceed in recovering the situation. I thought another section in the FAQ could answer this directly. I propose something below and if it's acceptable I'll put in a PR:

---

## Help! I lost my settings/subscriptions/media/everything!

Subscriptions and metadata can be mostly recovered if you have taken any of the steps from 'How do I keep my data when changing phone?', please see the answer there. However if you have not done that your options are more limited:

* Attempt to recover the sqlite database. AntennaPod may have written a file CorruptedDatabaseBackup.db to its app storage directory. There are guides online for how to recover a database. If you succeed in repairing it use the "Import Database" feature under Settings-Storage to reload it.
* You can see the titles of any podcast you recently downloaded in the 'files/media' dir under the app storage dir. From this list you can manually re-add the subscriptions. Any previously downloaded media still present on your device will not be recognised until you re-download an episode. Playback position, history and your queue will remain lost.

---

What I don't know for sure right now:

* If it is possible to repair the CorruptedDatabaseBackup.db file how can it be used by AntennaPod again? Use the Import Database function? What is stored in the database exactly? What would be recovered?
* If you re-subscribe to podcasts previously lost AntennaPod does not seem to register see the old media it previously downloaded in media dir, episodes have to be re-downloaded. However when you do re-download it adds a small (64kb) file e.g. "ORIGINAL-1.mp3" in the media dir and is then able to play the full episode, presumably from the old 'ORIGINAL.mp3' media file. So it seems the best advice is to leave your old media files in place (if any)? Will those old files be cleaned up eventually even if not re-downloaded?
* Are there any other ways to recover?

Thanks.

**Comment by keunes** [comment]
Hi @Ian2020
It's been a while, but I just prepared an update of the website documentation. I included also a page on data recovery after a corrupted database, as you requested. It would be great if you could share your feedback if you have any!
A preview of the page is available here: https://deploy-preview-138--antennapod-test.netlify.app/documentation/bugs-first-aid/database-error

**Comment by Ian2020** [comment]
It looks great! Thank you for making this, it will be a massive help for the unfortunate users. I myself have not had this issue since, it does seem very rare and must be some nasty race condition.
