### ISSUE TITLE
Update 'Other cool features' section

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#4]
- [ ] New features have been introduced which we might include on the website as well.
- [x] Also, the formatting should be redone to look pretty on mobile too.

![screenshot_2015-11-05-00-35-11](https://cloud.githubusercontent.com/assets/11229646/10964229/f4d19e6c-83a5-11e5-8ca5-e7fc1f4578e1.png)
- [ ] Maybe we can make the features clickable to display a small explanation or screen image ([HTML5 details element](http://html5doctor.com/the-details-and-summary-elements/); [CSS transitions](http://www.w3schools.com/css/css3_transitions.asp); [Animation.css](https://github.com/daneden/animate.css)).

**Comment by TomHennen** [comment]
I agree. I don't want to list the features new in 1.4 until it's released to the public though.

**Comment by keunes** [comment]
Mobile formatting should be improved as per #8
@TomHennen Should we start make a quick list of the new features so that we can publish as soon as 1.5 is out on Google Play? Anything I'm missing (or too much) here?

- remove 'Streaming' (is already in the 'Features' section)
- Vodcast support
- Favourites
- Localised interface
- Access iTunes database
- Downmix to mono output
- Powerful download automation
- Automate deleting episodes

**Comment by TomHennen** [comment]
Hmm, ideally the features should just pull from the changelog, but we've been doing a bad job of keeping that updated.

I feel like we should use US english and not UK (e.g. Favorites not Favourites, Localized not Localised).  Admittedly I'm in the US, so I'm biased, but most of our users are also in the US, so it might make more sense?

If you see a new feature added that wasn't put in the changelog, please feel free to issue a PR updating it.

**Comment by keunes** [comment]
> the features should just pull from the changelog

That'd be cool indeed, that would require very conscious wording of the changelog and some form of filtering ('cause UI fixes aren't necessarily 'features'). A little too complex I'm afraid.

We could, however, [create a dynamic section](http://stackoverflow.com/a/26454035) with the latest release version and a 'what's new' block. Yet looking around on [AP's releases page](https://github.com/AntennaPod/AntennaPod/releases) I saw that there's no release notes either, plus the [latest release tag](https://github.com/AntennaPod/AntennaPod/releases/latest) still forwards to AP v. 1.0.

> I feel like we should use US english and not UK

To be honest I find US English ugly, but given your argument + the fact that the app itself also has US English as standard, it does make sense. Will take US spelling when actually doing the PR.

**Comment by repat** [comment]
I'd be willing to help out on some stuff but been removed from the organization? 🤔

**Comment by keunes** [comment]
@repat Thanks for the offer :) ByteHamster updated the organisation.
@ByteHamster would you mind (re-)adding repat to the website team?

**Comment by ByteHamster** [comment]
Done. I updated the organization permissions to use teams (we have a forum there to communicate) and deleted people who I thought are no longer interested in contributing.
