### ISSUE TITLE
No cert for www

### ISSUE THREAD

**Issue by roshavagarga** [AntennaPod/antennapod.github.io#49]
According to [this](https://github.com/Podcastindex-org/web-ui/pull/35).

**Comment by ByteHamster** [comment]
Thanks for cross-posting this. It's a known issue with GitHub pages: https://github.com/isaacs/github/issues/1675

For now, it was enough to switch the "custom domain" setting of the repo to "www.antennapod.org" and back. Let's see how long that will keep working.
