### ISSUE TITLE
Use Netlify to create to create 'live previews' (?)

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#72]
I don't feel super comfortable making changes to the website, as I'm never sure what I'm doing will work or might mess up something. Would it be possible to connect & use Netlify for creating automatic full-site previous of branches and commits? The 'starter' account is free and it seems like it would do the job.
https://www.netlify.com/products/build/

**Comment by ByteHamster** [comment]
I feel like administering another service would be more work than working out how to build it locally. How about just configuring the existing CI task to upload a zip file of the finished website?

**Comment by keunes** [comment]
It really seems [easy peasy](https://www.netlify.com/blog/2020/04/02/a-step-by-step-guide-jekyll-4.0-on-netlify/) - just a matter of creating a Netlify account and linking up with the right GitHub repo & branch. Would you mind if I give it a try? (It's slightly more cumbersome to check and get feedback from others, but indeed a zip file could also work.)

**Comment by ByteHamster** [comment]
The problem in our case is that we build the site using CI and only then commit the generated html to a branch. That's different to other Jekyll sites that can directly be picked up by GitHub Pages from any branch (we use more complex plugins). Not sure if Netlify is different there.

Feel free to experiment, though, as long as the website does not get broken ^^

**Comment by keunes** [comment]
This now works :)
