### ISSUE TITLE
Ruby build depricated

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#74]
In the build logs I just saw the following:
```
Run actions/setup-ruby@v1
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
```

Could that be why my recent commits are failing? @ByteHamster

**Comment by ByteHamster** [comment]
I think the interesting part of that error message actually is `/home/runner/work/antennapod.github.io/antennapod.github.io/_i18n/en.yml): did not find expected key while parsing a block mapping at line 50 column 3 (Psych::SyntaxError)`. I haven't looked at line 50 of that file yet, though.

**Comment by keunes** [comment]
Thanks! Found it, I think. The error message lists the wrong line & column (https://github.com/ruby/psych/issues/190), but under 'donate' I added double quotes that should be escaped.

**Comment by keunes** [comment]
Yes, it builds correctly now! 🎉 Thanks for the pointer.
