### ISSUE TITLE
Documentation should address deletion policy more clearly

### ISSUE THREAD

**Issue by amandabee** [AntennaPod/antennapod.github.io#85]
There's no documentation at https://antennapod.org/ which makes it hard to point new users in the right direction. In particular I'm trying to figure out what the expected deletion behaviour is. I often find that if I mark an episode as "Played" it stays in my queue and isnt' downloaded. There are a lot of reasons I might mark something played:

+ this particular episode was already broadcast on the radio
+ I listened to it in the car on someone else's phone
+ it's a re-run
+ It's a terrible episode and I don't want to keep thinking maybe I should listen to it
+ I listened to the end but the closing credits are so long that Antennapod thinks I didn't finish it.

I don't know what is *supposed* to happen and I can't find documentation to figure out what should happen so I don't know if it's my settings or a bug or a combination. But I would expect that all completed episodes would be treated the same, whether they're completed because they played to the end or because they played halfway and I marked them played.  More clear documentation of the default flow and places where changing settings will impact the default flow would help me make the most of Antennapod.

A friend started using Antennapod at my suggestion and they're also confused/frustrated and I'd like to point them to some documentation instead of walking them through what I do and puzzling it out together.

**Comment by comradekingu** [comment]
What is the use-case of treating "marked as played" as different from "played"?

**Comment by keunes** [comment]
There now is documentation and this ticket is 2 years old. I will review when I have the time. Questions/comments on the app should be discussed in the appropriate repo.
