### ISSUE TITLE
Unnecessary menu button when on mobile

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#9]
As the title says. When clicking on the menu, nothing happens/appears.

![screenshot_2015-11-05-00-35-11](https://cloud.githubusercontent.com/assets/11229646/10964229/f4d19e6c-83a5-11e5-8ca5-e7fc1f4578e1.png)

**Comment by s2bu** [comment]
On the latest version I downloaded (from FDroid), I went through all the screens, but did not see a spurious non-functioning menu button. Is this still an issue? If so, what screen is it on? If not maybe this can be closed.

**Comment by s2bu** [comment]
Oops, sorry forgot version details:
Version:	1.7.0
Commit:	4ba36b82
running on antique but functional KitKat Samsung G4

**Comment by mfietz** [comment]
That doesn't look like any of our screens. Looks more like a website...

**Comment by keunes** [comment]
@s2bu Please note that this is an issue in the *website repository*. This is not the app repository. (Just 7 issues for whole AntennaPod, if only :) )

If you go to www.antennapod.org on your mobile device, or press ctrl+shift+m in Firefox, you will be able to see the issue.
